/** i18n namespace: chat, ws (23 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "chat.direct": "私人對話",
  "chat.group": "行程群組",
  "chat.loadRoomsError": "無法載入對話列表。",
  "chat.loadMessagesError": "無法載入訊息。",
  "chat.wsForbidden": "連線被拒：你沒有此對話的存取權限。",
  "chat.wsFailed": "無法建立連線，請重新登入後再試。",
  "chat.sendFailed": "傳送失敗（{code}）。",
  "chat.rooms": "對話",
  "chat.noRooms": "還沒有對話。",
  "chat.noRoomsHint": "申請行程被接受後會自動開啟。",
  "chat.memberCount": "{count} 位成員",
  "chat.selectRoom": "選擇一個對話開始聊天。",
  "chat.online": "在線",
  "chat.offline": "離線",
  "chat.statusOpen": "已連線",
  "chat.statusConnecting": "連線中…",
  "chat.statusClosed": "已中斷",
  "chat.noMessages": "還沒有訊息，打個招呼吧！",
  "chat.messageDeleted": "此訊息已被刪除",
  "chat.peerTyping": "對方正在輸入…",
  "chat.composerPlaceholder": "輸入訊息…（每秒最多 2 則）",
  "chat.send": "傳送",
  "ws.safetyHint.possible_phone": "為保障私隱，請避免在建立信任前交換聯絡方式或進行金錢交易。",
} as const;

export const en = {
  "chat.direct": "Direct message",
  "chat.group": "Trip group",
  "chat.loadRoomsError": "Could not load your conversations.",
  "chat.loadMessagesError": "Could not load messages.",
  "chat.wsForbidden": "Connection refused: you do not have access to this conversation.",
  "chat.wsFailed": "Could not connect. Please log in again and retry.",
  "chat.sendFailed": "Could not send ({code}).",
  "chat.rooms": "Conversations",
  "chat.noRooms": "No conversations yet.",
  "chat.noRoomsHint": "One opens automatically when your application is accepted.",
  "chat.memberCount": "{count} members",
  "chat.selectRoom": "Pick a conversation to start chatting.",
  "chat.online": "Online",
  "chat.offline": "Offline",
  "chat.statusOpen": "Connected",
  "chat.statusConnecting": "Connecting…",
  "chat.statusClosed": "Disconnected",
  "chat.noMessages": "No messages yet — say hello!",
  "chat.messageDeleted": "This message was deleted",
  "chat.peerTyping": "Typing…",
  "chat.composerPlaceholder": "Type a message… (max 2 per second)",
  "chat.send": "Send",
  "ws.safetyHint.possible_phone": "To protect your privacy, avoid sharing contact details or sending money before trust is established.",
};
