/** i18n namespace: cityPicker (8 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "cityPicker.placeholder": "選擇城市（選填）",
  "cityPicker.searchPlaceholder": "輸入城市名稱…",
  "cityPicker.listLabel": "城市建議",
  "cityPicker.typeToSearch": "輸入至少 2 個字元開始搜尋。",
  "cityPicker.noMatch": "找不到相符的城市。你可以留空，或改用更完整的拼寫。",
  "cityPicker.clear": "清除已選城市",
  "cityPicker.historyHint": "選填。填寫去過的城市可提高配對分數；留空不會影響發佈。",
  "cityPicker.tripHint": "選填。從清單選擇可讓系統正確比對，手動輸入的拼寫無法驗證。",
} as const;

export const en = {
  "cityPicker.placeholder": "Choose a city (optional)",
  "cityPicker.searchPlaceholder": "Type a city name…",
  "cityPicker.listLabel": "City suggestions",
  "cityPicker.typeToSearch": "Type at least 2 characters to search.",
  "cityPicker.noMatch": "No matching city. You can leave it blank, or try a fuller spelling.",
  "cityPicker.clear": "Clear the selected city",
  "cityPicker.historyHint": "Optional. Adding cities you have visited improves your match score; leaving it blank will not block publishing.",
  "cityPicker.tripHint": "Optional. Picking from the list is what lets the system match correctly — a typed spelling cannot be verified.",
};
