/** i18n namespace: common, meta, footer, nav, authGate, disclaimer (24 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "common.loading": "載入中…",
  "common.reload": "重新載入",
  "common.cancel": "取消",
  "common.close": "關閉",
  "common.all": "全部",
  "common.none": "無",
  "meta.title": "Trip Mate — 旅伴配對平台",
  "meta.description": "Trip Mate 是一個為香港旅客而設的旅伴配對平台：發佈行程、依旅遊足跡配對志同道合的旅伴，並安全地即時通訊。",
  "footer.disclaimer": "Trip Mate · 本平台僅提供資訊媒合服務。請參閱《私隱政策》及《服務條款》。",
  "nav.trips": "探索行程",
  "nav.newTrip": "發佈行程",
  "nav.chat": "訊息",
  "nav.profile": "我的檔案",
  "nav.admin": "管理",
  "nav.logout": "登出",
  "nav.login": "登入",
  "nav.register": "免費註冊",
  "nav.language": "語言",
  "authGate.title": "請先登入",
  "authGate.body": "Trip Mate 只向已註冊用戶展示旅伴資訊，以保障社群安全。",
  "authGate.action": "登入",
  "disclaimer.heading": "安全提示：",
  "disclaimer.body": "本平台僅提供資訊媒合服務，線下見面與旅遊期間之個人人身安全、財物損失及消費糾紛，平台概不承擔法律責任。",
  "disclaimer.noMoney": "切勿在建立信任前進行金錢交易。",
} as const;

export const en = {
  "common.loading": "Loading…",
  "common.reload": "Reload",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.all": "All",
  "common.none": "None",
  "meta.title": "Trip Mate — Travel companion matching",
  "meta.description": "Trip Mate is a travel-companion matching platform for Hong Kong travellers: post a trip, get matched with like-minded companions by travel history, and chat safely in real time.",
  "footer.disclaimer": "Trip Mate · This platform only provides information matching. See our Privacy Policy and Terms of Service.",
  "nav.trips": "Explore trips",
  "nav.newTrip": "Post a trip",
  "nav.chat": "Messages",
  "nav.profile": "My profile",
  "nav.admin": "Admin",
  "nav.logout": "Log out",
  "nav.login": "Log in",
  "nav.register": "Sign up free",
  "nav.language": "Language",
  "authGate.title": "Please log in",
  "authGate.body": "Trip Mate only shows traveller profiles to registered users, to keep the community safe.",
  "authGate.action": "Log in",
  "disclaimer.heading": "Safety notice: ",
  "disclaimer.body": "This platform only provides information matching. It accepts no legal liability for personal safety, loss of property or disputes arising from meeting offline or during travel.",
  "disclaimer.noMoney": "Never send money before trust is established.",
};
