/** i18n namespace: gender, budget (7 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "budget.BUDGET": "省錢",
  "budget.MODERATE": "中等",
  "budget.LUXURY": "豪華",
  "gender.MALE": "男",
  "gender.FEMALE": "女",
  "gender.OTHER": "其他",
  "gender.ANY": "不限",
} as const;

export const en = {
  "budget.BUDGET": "Budget",
  "budget.MODERATE": "Moderate",
  "budget.LUXURY": "Luxury",
  "gender.MALE": "Male",
  "gender.FEMALE": "Female",
  "gender.OTHER": "Other",
  "gender.ANY": "Any",
};
