/** i18n namespace: home (20 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "home.badge": "香港 · 旅伴配對",
  "home.titleLine1": "找到與你同步的",
  "home.titleLine2": "下一位旅伴",
  "home.intro": "Trip Mate 讓你發佈行程、說明想去的地方與旅遊風格。系統會依據你的旅遊足跡與興趣，推薦最合拍的旅伴；內建即時通訊、封鎖與檢舉機制，讓配對過程安全可控。",
  "home.ctaStart": "立即開始",
  "home.ctaBrowse": "瀏覽行程",
  "home.stat.steps.value": "3 步",
  "home.stat.steps.label": "發佈 → 配對 → 對話",
  "home.stat.pdpo.value": "PDPO",
  "home.stat.pdpo.label": "符合香港私隱條例",
  "home.stat.rate.value": "2 msg/s",
  "home.stat.rate.label": "防騷擾速率限制",
  "home.feature.match.title": "智能配對",
  "home.feature.match.body": "依你的旅遊足跡、風格標籤與語言，為每篇行程計算配對分數，並解釋推薦原因。",
  "home.feature.chat.title": "安全對話",
  "home.feature.chat.body": "只有房間成員能收發訊息；封鎖後即時失效，偵測到電話號碼時主動提醒。",
  "home.feature.privacy.title": "私隱優先",
  "home.feature.privacy.body": "只收集必要資料、足跡可設公開或私人，並支援一鍵註銷帳號與資料匿名化。",
  "home.feature.review.title": "評價制度",
  "home.feature.review.body": "只有真正一起出遊過的旅伴才能互相評價，杜絕刷分與惡意負評。",
} as const;

export const en = {
  "home.badge": "Hong Kong · Travel companion matching",
  "home.titleLine1": "Find the next",
  "home.titleLine2": "traveller in sync with you",
  "home.intro": "Trip Mate lets you post a trip and describe where you want to go and how you like to travel. We match you with compatible companions based on your travel history and interests, with built-in chat, blocking and reporting to keep it safe.",
  "home.ctaStart": "Get started",
  "home.ctaBrowse": "Browse trips",
  "home.stat.steps.value": "3 steps",
  "home.stat.steps.label": "Post → Match → Chat",
  "home.stat.pdpo.value": "PDPO",
  "home.stat.pdpo.label": "Compliant with HK privacy law",
  "home.stat.rate.value": "2 msg/s",
  "home.stat.rate.label": "Anti-harassment rate limit",
  "home.feature.match.title": "Smart matching",
  "home.feature.match.body": "Every trip gets a match score from your travel history, style tags and languages — with the reasons spelled out.",
  "home.feature.chat.title": "Safe conversations",
  "home.feature.chat.body": "Only room members can send or receive messages. Blocks take effect immediately, and phone numbers are flagged as you type.",
  "home.feature.privacy.title": "Privacy first",
  "home.feature.privacy.body": "We collect only what is needed, your travel history can be public or private, and you can erase or anonymise your account in one step.",
  "home.feature.review.title": "Verified reviews",
  "home.feature.review.body": "Only travellers who actually completed a trip together can rate each other, which rules out score-gaming and drive-by negativity.",
};
