/** i18n namespace: reviewTag (8 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "reviewTag.PUNCTUAL": "準時",
  "reviewTag.FRIENDLY": "友善",
  "reviewTag.GOOD_PLANNER": "規劃周全",
  "reviewTag.FLEXIBLE": "隨和",
  "reviewTag.TIDY": "整潔",
  "reviewTag.FUN": "有趣",
  "reviewTag.KNOWLEDGEABLE": "見識廣",
  "reviewTag.RESPECTFUL": "尊重他人",
} as const;

export const en = {
  "reviewTag.PUNCTUAL": "Punctual",
  "reviewTag.FRIENDLY": "Friendly",
  "reviewTag.GOOD_PLANNER": "Good planner",
  "reviewTag.FLEXIBLE": "Flexible",
  "reviewTag.TIDY": "Tidy",
  "reviewTag.FUN": "Fun",
  "reviewTag.KNOWLEDGEABLE": "Knowledgeable",
  "reviewTag.RESPECTFUL": "Respectful",
};
