/** i18n namespace: contentRejected, content_field (9 keys).
 *
 * Generated by splitting the flat dictionary (D5). `zh-HK` is the key
 * source; `en` is declared `Record<MessageKey, string>` so a missing
 * translation remains a compile error.
 */
export const zhHK = {
  "contentRejected.content_rejected": "這段內容含有不符合社群規範的資訊，請修改後再試。",
  "contentRejected.content_filter_unavailable": "內容審核服務暫時無法使用，請稍後再試。",
  "content_field.title": "標題",
  "content_field.description": "行程說明",
  "content_field.nickname": "暱稱",
  "content_field.bio": "個人簡介",
  "content_field.comment": "評價內容",
  "content_field.message": "訊息",
  "content_field.summary": "足跡摘要",
} as const;

export const en = {
  "contentRejected.content_rejected": "This text contains information that breaks our community rules. Please edit it and try again.",
  "contentRejected.content_filter_unavailable": "The content review service is temporarily unavailable. Please try again shortly.",
  "content_field.title": "Title",
  "content_field.description": "Trip description",
  "content_field.nickname": "Nickname",
  "content_field.bio": "Bio",
  "content_field.comment": "Review",
  "content_field.message": "Message",
  "content_field.summary": "Summary",
};
