"""add notifications table

Revision ID: 390180f865f7
Revises: c75898845cf5
Create Date: 2026-09-21 04:10:59.388298

Notes on the FK delete rules (they encode product decisions, not just schema):

* `recipient_profile_id` CASCADE — erasing a user removes their own
  notifications, as the right-to-erasure requires.
* `actor_profile_id` SET NULL — erasing the *actor* must NOT delete the
  recipient's notification, or a third party's deletion would silently rewrite
  someone else's history.
* `trip_post_id` / `chat_room_id` SET NULL — the notification survives the
  referenced object, so a deleted trip does not erase the record of it.

Also: the autogenerated `server_default=sa.text('(CURRENT_TIMESTAMP)')` is
SQLite-only and fails on PostgreSQL, so it is replaced with the dialect-neutral
`sa.func.now()`.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '390180f865f7'
down_revision = 'c75898845cf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('notifications',
    sa.Column('recipient_profile_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('APPLICATION_RECEIVED', 'APPLICATION_ACCEPTED', 'APPLICATION_REJECTED', 'NEW_MESSAGE', 'REVIEW_RECEIVED', name='notification_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('actor_profile_id', sa.Uuid(), nullable=True),
    sa.Column('trip_post_id', sa.Uuid(), nullable=True),
    sa.Column('chat_room_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['actor_profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_post_id'], ['trip_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_actor_profile_id'), ['actor_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_chat_room_id'), ['chat_room_id'], unique=False)
        batch_op.create_index('ix_notifications_message_dedupe', ['recipient_profile_id', 'chat_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_profile_id'), ['recipient_profile_id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_read_created', ['recipient_profile_id', 'read_at', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_trip_post_id'), ['trip_post_id'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_trip_post_id'))
        batch_op.drop_index('ix_notifications_recipient_read_created')
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_profile_id'))
        batch_op.drop_index('ix_notifications_message_dedupe')
        batch_op.drop_index(batch_op.f('ix_notifications_chat_room_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_actor_profile_id'))

    op.drop_table('notifications')
