"""add audit logs table

Revision ID: 619d0806a0cd
Revises: cafc59ae9ecc
Create Date: 2026-09-21 05:45:28.839957

Append-only audit trail for the four security-relevant categories the Security
Spec names: blocking, reporting, erasure, and administrator action.

Notes on the FK and the columns (they encode product decisions, not just schema):

* `actor_profile_id` is `SET NULL`, never `CASCADE`. If erasing a user also
  erased the record of what they did, the right to erasure would double as a way
  to launder an abuse history. The entry survives with a null actor: the event is
  kept, the identity is not.

* `target_id` is deliberately **not** a foreign key. The target is frequently the
  row the audited action deletes (a block that was removed, an account that was
  erased), so a real FK would either cascade the evidence away or block the
  delete. `target_type` records which table it referred to.

* There is no `updated_at` and no `deleted_at`: an audit row that can be edited
  is not evidence. Nothing in the application updates or deletes this table.

* The autogenerated `server_default=sa.text('(CURRENT_TIMESTAMP)')` is
  SQLite-only and fails on PostgreSQL, so it is replaced with the dialect-neutral
  `sa.func.now()`.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '619d0806a0cd'
down_revision = 'cafc59ae9ecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'audit_logs',
        sa.Column('actor_profile_id', sa.Uuid(), nullable=True),
        sa.Column(
            'action',
            sa.Enum(
                'USER_BLOCKED', 'USER_UNBLOCKED', 'REPORT_SUBMITTED',
                'REPORT_STATUS_CHANGED', 'ACCOUNT_DELETED', 'ACCOUNT_ANONYMIZED',
                'ADMIN_QUEUE_VIEWED',
                name='audit_action', native_enum=False, length=21,
            ),
            nullable=False,
        ),
        sa.Column('target_type', sa.String(length=40), nullable=True),
        sa.Column('target_id', sa.Uuid(), nullable=True),
        sa.Column('detail', sa.JSON(), nullable=True),
        sa.Column('request_id', sa.String(length=64), nullable=True),
        sa.Column('ip_address', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=300), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['actor_profile_id'], ['profiles.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_profile_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index('ix_audit_logs_action_created')

    op.drop_table('audit_logs')
