"""trip post tags join table

Revision ID: cafc59ae9ecc
Revises: 390180f865f7
Create Date: 2026-09-21 05:19:03.463120

Replaces the `trip_posts.tags` JSON column with a `trip_post_tags` row-per-tag
table, so tag filtering becomes an indexed `EXISTS` instead of a scan capped at
1000 rows held in memory. The old filter silently dropped matches on a larger
dataset and reported a `total` that was only true inside the scan window.

The upgrade **backfills before dropping**, so no tag data is lost, and the
downgrade rebuilds the JSON arrays from the join table — reversible in practice,
not just in principle.

Two details the autogenerated version got wrong and are fixed here, mirroring
the notifications migration:

* `sa.JSON()` rather than the autogenerated `sqlite.JSON()` in the downgrade —
  the dialect-specific type would make the same migration fail on PostgreSQL.
* The re-added `tags` column needs a `server_default`, because adding a NOT NULL
  column to a non-empty table has no valid value otherwise. The default is left
  in place deliberately: dropping it on SQLite needs another full table rebuild,
  and at head this column does not exist at all, so `alembic check` never sees it.
"""
from __future__ import annotations

import json

from alembic import op
import sqlalchemy as sa


revision = 'cafc59ae9ecc'
down_revision = '390180f865f7'
branch_labels = None
depends_on = None

TAG_MAX_LENGTH = 40


def _normalise(values) -> list[str]:
    """Canonical tag form, intentionally duplicated from the application.

    A migration must keep producing the same rows even if the application helper
    is later renamed, moved or changed — so it does not import it.
    """
    seen: set[str] = set()
    out: list[str] = []
    for raw in values or []:
        if raw is None:
            continue
        tag = str(raw).strip().upper()[:TAG_MAX_LENGTH]
        if tag and tag not in seen:
            seen.add(tag)
            out.append(tag)
    return out


def upgrade() -> None:
    op.create_table(
        'trip_post_tags',
        sa.Column('trip_post_id', sa.Uuid(), nullable=False),
        sa.Column('tag', sa.String(length=TAG_MAX_LENGTH), nullable=False),
        sa.ForeignKeyConstraint(['trip_post_id'], ['trip_posts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('trip_post_id', 'tag'),
    )
    with op.batch_alter_table('trip_post_tags', schema=None) as batch_op:
        batch_op.create_index('ix_trip_post_tags_tag', ['tag'], unique=False)

    # --- backfill, before the source column disappears ---------------------
    bind = op.get_bind()
    rows = bind.execute(sa.text('SELECT id, tags FROM trip_posts')).fetchall()

    payload = []
    for post_id, raw in rows:
        if raw is None:
            continue
        if isinstance(raw, (str, bytes, bytearray)):
            # SQLite stores JSON as text; PostgreSQL's JSON type is already
            # decoded by the driver, so only decode when we were handed a string.
            try:
                raw = json.loads(raw)
            except (TypeError, ValueError):
                raw = []
        # `str()` because raw-SQL parameters carry no type information, so a
        # uuid.UUID would reach the SQLite driver unconverted.
        payload.extend(
            {'trip_post_id': str(post_id), 'tag': tag} for tag in _normalise(raw)
        )

    if payload:
        bind.execute(
            sa.text(
                'INSERT INTO trip_post_tags (trip_post_id, tag) '
                'VALUES (:trip_post_id, :tag)'
            ),
            payload,
        )

    with op.batch_alter_table('trip_posts', schema=None) as batch_op:
        batch_op.drop_column('tags')


def downgrade() -> None:
    bind = op.get_bind()

    with op.batch_alter_table('trip_posts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('tags', sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    rows = bind.execute(
        sa.text('SELECT trip_post_id, tag FROM trip_post_tags ORDER BY trip_post_id, tag')
    ).fetchall()
    grouped: dict[str, list[str]] = {}
    for post_id, tag in rows:
        grouped.setdefault(str(post_id), []).append(tag)

    for post_id, tags in grouped.items():
        bind.execute(
            sa.text('UPDATE trip_posts SET tags = :tags WHERE id = :id'),
            {'tags': json.dumps(tags), 'id': post_id},
        )

    with op.batch_alter_table('trip_post_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_trip_post_tags_tag')

    op.drop_table('trip_post_tags')
