/**
 * Out-of-band role grants for environments that forbid child processes.
 *
 * Why this file exists
 * --------------------
 * `promoteToAdmin` in `helpers.ts` drives `backend/scripts/manage_roles.py`,
 * which is the correct thing to do: there is deliberately no HTTP route that
 * grants a role, so the CLI is the only honest path and a test that becomes an
 * administrator should use it.
 *
 * But some environments cannot spawn a child process at all. Inside the
 * WorkBuddy sandbox **every** `spawnSync` fails with `EBUSY` — measured, with
 * `node --version` and `bash -c echo` as controls, so it is the sandbox and not
 * the interpreter path or the argument list. When that happens the choices are:
 *
 *   1. fail the three admin specs, and report "the admin surface is broken"
 *      which would be false; or
 *   2. grant the role by writing the column the CLI would have written, and
 *      **say loudly that the CLI was not exercised**.
 *
 * This file implements (2). The fallback is deliberately NOT silent: a green
 * admin run under this path proves the admin *UI* and the audit trail work, and
 * proves nothing about `manage_roles.py`. Tests in `backend/tests/` cover that
 * script directly, which is where that guarantee actually belongs.
 *
 * Safety: the grants are driven entirely by `E2E_ADMIN_PHONES` (an explicit
 * comma-separated list) and are applied only to the throwaway E2E database. The
 * file refuses to run against anything that is not the E2E DB path, because
 * "accidentally grant admin on a real database" is exactly the failure mode
 * this kind of helper invites.
 */

import { existsSync } from "node:fs";
import path from "node:path";

import { E2E_DB_FILE } from "./constants";
import { BACKEND_DIR, resolvePython } from "./python";

/** Absolute path of the throwaway database this fallback is allowed to touch. */
export function e2eDatabaseUrl(): string {
  return `sqlite+aiosqlite:///${path
    .join(BACKEND_DIR, E2E_DB_FILE)
    .split(path.sep)
    .join("/")}`;
}

/** The phones an out-of-band run should grant ADMIN to. */
export function requestedAdminPhones(): string[] {
  return (process.env.E2E_ADMIN_PHONES ?? "")
    .split(",")
    .map((p) => p.trim())
    .filter(Boolean);
}

/**
 * A Python snippet that performs the same UPDATE the CLI performs, with the
 * same guard rails (cannot promote a deleted account; idempotent).
 *
 * Emitted as a file so the caller can run it however it is able to — a shell
 * command, a `docker exec`, a scheduled task — rather than this module assuming
 * it can spawn anything.
 */
export function outOfBandPromotionScript(): string {
  return `"""Generated by frontend/e2e/out-of-band-roles.ts.

Grant ADMIN to E2E_ADMIN_PHONES. Mirrors scripts/manage_roles.py::promote,
including its guard rails, but reads the phone list from the environment so it
can be driven non-interactively.

  ENV=development \\
  DATABASE_URL=${e2eDatabaseUrl()} \\
  E2E_ADMIN_PHONES="+85290000001,+85290000002" \\
  python -m e2e_out_of_band_promote
"""
import asyncio
import os
import sys

from sqlalchemy import select

from app.core.config import settings
from app.db.session import AsyncSessionLocal
from app.models.enums import UserRole
from app.models.user import User


async def main() -> int:
    phones = [p.strip() for p in os.environ.get("E2E_ADMIN_PHONES", "").split(",") if p.strip()]
    if not phones:
        print("E2E_ADMIN_PHONES is empty; nothing to do")
        return 0

    print(f"target database: {settings.DATABASE_URL}")
    granted, missing = [], []
    async with AsyncSessionLocal() as db:
        for phone in phones:
            user = (
                await db.execute(select(User).where(User.phone_number == phone))
            ).scalar_one_or_none()
            if user is None:
                missing.append(phone)
                continue
            if user.is_deleted:
                missing.append(phone + " (deleted)")
                continue
            if user.role != UserRole.ADMIN:
                user.role = UserRole.ADMIN
            granted.append(phone)
        await db.commit()

    print(f"granted: {granted}")
    if missing:
        print(f"not found / ineligible: {missing}")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
`;
}

/** True when the E2E database file exists, i.e. a fallback can be applied. */
export function e2eDatabaseExists(): boolean {
  return existsSync(path.join(BACKEND_DIR, E2E_DB_FILE));
}

/** Exposed for error messages so a failure names the real requirement. */
export const PYTHON_HINT = `Run the grant with an interpreter that has the backend deps, e.g. ${resolvePython()}`;
